### ISSUE TITLE
LocalPreferences.toml got reset

### ISSUE THREAD

**Issue by Technici4n** [epfl-matmat/AiidaDFTK.jl#16]
At some point my local preferences got reset from
```toml
[DFTK]
DFTK_threads = 1

[HDF5]
libhdf5 = "/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5.so"
libhdf5_hl = "/usr/lib/x86_64-linux-gnu/hdf5/openmpi/libhdf5_hl.so"

[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
cclibs = []
libmpi = "libmpi"
mpiexec = "mpiexec"
preloads = []
```

to just
```toml
[DFTK]
DFTK_threads = 1
```

I am not sure what exactly happened. I might have killed a julia process that was precompiling something, but that might not be related.
I suspect at least that AiidaDFTK modifies the local preferences during precompilation. (EDIT: This is indeed the case when precompiling with MPI. That is already a bad idea because it tends to deadlock, but it can happen.)

It's worth investigating.
